from django.conf.urls import patterns, url, include
from timebook import views

urlpatterns = patterns('timebook.views',
                       url(r'^$', 'api_root',
                           name='API-Root'),
                       url(r'^customers/$', views.CustomerList.as_view(),
                           name='customer-list'),
                       url(r'^customers/(?P<pk>[0-9]+)/$',
                           views.CustomerDetail.as_view(),
                           name='customer-detail'),
                       url(r'^customers/(?P<pk>[0-9]+)/jobs/$',
                           views.JobsOnCustomerList.as_view(),
                           name='jobsoncustomer-list'),
                       url(r'^jobs/$', views.JobList.as_view(),
                           name='job-list'),
                       url(r'^jobs/(?P<pk>[0-9]+)/$',
                           views.JobDetail.as_view(),
                           name='job-detail'),
                       url(r'^jobs/(?P<pk>[0-9]+)/times/$',
                           views.TimeOnJobList.as_view(),
                           name='timeonjob-list'),
                       url(r'^workers/$', views.WorkerList.as_view(),
                           name='worker-list'),
                       url(r'^workers/(?P<pk>[0-9]+)/$',
                           views.WorkerDetail.as_view(),
                           name='worker-detail'),
                       url(r'^workers/(?P<pk>[0-9]+)/times/$',
                           views.WorkedOnList.as_view(),
                           name='workedon-list'),
                       url(r'^timetypes/$', views.TimeTypeList.as_view(),
                           name='timetype-list'),
                       url(r'^timetypes/(?P<pk>[0-9]+)/$',
                           views.TimeTypeDetail.as_view(),
                           name='timetype-detail'),
                       url(r'^timetypes/(?P<pk>[0-9]+)/times$',
                           views.TimeOfTypeList.as_view(),
                           name='timeoftype-list'),
                       url(r'^times/$', views.TimeList.as_view(),
                           name='time-list'),
                       url(r'^times/(?P<pk>[0-9]+)/$',
                           views.TimeDetail.as_view(),
                           name='time-detail'),
                       )
